# 📘 NumPy — Complete Beginner's Guide

> **NumPy** = **Num**erical **Py**thon  
> It is the fundamental library for numerical computing in Python.  
> Almost every data science / ML library (Pandas, Matplotlib, Scikit-learn, TensorFlow) is built **on top of NumPy**.

---

## 1. What is NumPy & Why Use It?

### 🤔 Think of it this way...

Imagine you have a list of 1 million exam scores and you want to add 5 bonus marks to each student.

**With plain Python:** You need a slow loop  
**With NumPy:** Just `scores + 5` — done! No loop needed! 🚀

| Feature | Python List | NumPy Array |
|---------|------------|-------------|
| Speed | Slow (loops) | 50-100x faster |
| Memory | More memory | Less memory |
| Math Operations | Manual loops | Built-in vectorized |
| Multi-dimensional | Nested lists (messy) | Clean ndarray |
| Used in ML/AI | ❌ Not directly | ✅ Foundation |

## 2. Installation & Import

In [1]:
# Install numpy (uncomment if needed)
# !pip install numpy

In [2]:
import numpy as np   # 'np' is the standard shorthand everyone uses
print(f"NumPy version: {np.__version__}")

NumPy version: 2.0.2


> 💡 **Why `np`?** It's a universal convention. When you see `np.` in any tutorial, book, or StackOverflow answer, they mean NumPy.

---

## 3. Creating Arrays

### 3.1 From a Python List

In [3]:
# 1-D Array (like a single row of data)
marks = np.array([85, 90, 78, 92, 88])
print("1-D Array:")
print(marks)

1-D Array:
[85 90 78 92 88]


In [4]:
# 2-D Array (like a table — rows and columns)
student_marks = np.array([
    [85, 90, 78],    # Student 1: Math, Science, English
    [92, 88, 95],    # Student 2
    [67, 72, 80]     # Student 3
])
print("2-D Array (Table):")
print(student_marks)

2-D Array (Table):
[[85 90 78]
 [92 88 95]
 [67 72 80]]


> 🧠 **Think of it like Excel:**  
> 1-D array = one row  
> 2-D array = a table with rows and columns  
> 3-D array = multiple tables (like sheets in Excel)

### 3.2 Using Built-in Functions

In [5]:
# All zeros — useful for initializing
zeros = np.zeros((2, 3))
print("Zeros:")
print(zeros)
print()

Zeros:
[[0. 0. 0.]
 [0. 0. 0.]]



In [6]:
# All ones
ones = np.ones((3, 3))
print("Ones:")
print(ones)
print()

Ones:
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]



In [7]:
# A specific value everywhere
fives = np.full((2, 4), 5)
print("Full (all 5s):")
print(fives)
print()

Full (all 5s):
[[5 5 5 5]
 [5 5 5 5]]



In [8]:
# Identity matrix (1s on diagonal, 0s elsewhere)
# Used a LOT in linear algebra and ML
identity = np.identity(4)
print("Identity Matrix (4x4):")
print(identity)

Identity Matrix (4x4):
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


### 3.3 Ranges and Sequences

In [9]:
# arange: like Python's range() but returns an array
numbers = np.arange(0, 10, 2)   # start=0, stop=10, step=2
print("arange(0, 10, 2):", numbers)

# Another example
count = np.arange(15)   # 0 to 14
print("arange(15):", count)

arange(0, 10, 2): [0 2 4 6 8]
arange(15): [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [10]:
# linspace: evenly spaced numbers between start and end
temperature = np.linspace(0, 100, 5)  # 5 values from 0 to 100
print("linspace(0, 100, 5):", temperature)

# 10 values between 1 and 4
lspace = np.linspace(1, 4, 10)
print("linspace(1, 4, 10):", lspace)

linspace(0, 100, 5): [  0.  25.  50.  75. 100.]
linspace(1, 4, 10): [1.         1.33333333 1.66666667 2.         2.33333333 2.66666667
 3.         3.33333333 3.66666667 4.        ]


> 💡 **When to use which?**
> - `arange` → you know the **step size** (e.g., count by 2s)
> - `linspace` → you know **how many values** you want (e.g., 5 evenly spaced)

### 3.4 Empty & Empty-like

In [11]:
# empty: creates array with whatever values are in memory (NOT zeros!)
empty = np.empty((2, 3))
print("Empty (random garbage values):")
print(empty)
print()

# empty_like: same shape/type as another array
template = np.array([1.0, 2.0, 3.0])
new_arr = np.empty_like(template)
print("Empty-like (same shape as template):")
print(new_arr)

Empty (random garbage values):
[[0. 0. 0.]
 [0. 0. 0.]]

Empty-like (same shape as template):
[1. 1. 1.]


> ⚠️ **Warning:** `np.empty()` does NOT give you zeros! It's faster than `np.zeros()` because it skips initialization, but the values are unpredictable.

---

## 4. Array Attributes

| Attribute | What it tells you | Example |
|-----------|------------------|--------|
| `.shape` | Dimensions (rows, cols) | `(3, 3)` |
| `.ndim` | Number of dimensions | `2` |
| `.size` | Total element count | `9` |
| `.dtype` | Data type | `int64` |
| `.itemsize` | Bytes per element | `8` |

In [12]:
student_marks = np.array([
    [85, 90, 78],
    [92, 88, 95],
    [67, 72, 80]
])

print(f"Shape (rows, cols): {student_marks.shape}")
print(f"Dimensions:         {student_marks.ndim}")
print(f"Total elements:     {student_marks.size}")
print(f"Data type:          {student_marks.dtype}")
print(f"Bytes per element:  {student_marks.itemsize}")

Shape (rows, cols): (3, 3)
Dimensions:         2
Total elements:     9
Data type:          int64
Bytes per element:  8


---

## 5. Indexing & Slicing

### 5.1 Basic Indexing (like picking items from a shelf)

In [13]:
marks = np.array([85, 90, 78, 92, 88])

print(f"First element:  {marks[0]}")
print(f"Last element:   {marks[-1]}")
print(f"Second element: {marks[1]}")

First element:  85
Last element:   88
Second element: 90


### 5.2 2-D Array Indexing

In [14]:
table = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])

# Element at row 0, column 1
print(f"table[0, 1] = {table[0, 1]}")

# Element at row 2, column 2
print(f"table[2, 2] = {table[2, 2]}")

# Modify a value
table[0, 1] = 25
print(f"After modification, table[0, 1] = {table[0, 1]}")

table[0, 1] = 20
table[2, 2] = 90
After modification, table[0, 1] = 25


> 🧠 **Remember:** `array[row, column]` — Row first, then column!

### 5.3 Slicing (getting a chunk of data)

In [15]:
marks = np.array([85, 90, 78, 92, 88, 76, 95])

print(f"First 3:       {marks[:3]}")
print(f"From index 2:  {marks[2:]}")
print(f"Every other:   {marks[::2]}")
print(f"Reversed:      {marks[::-1]}")

First 3:       [85 90 78]
From index 2:  [78 92 88 76 95]
Every other:   [85 78 88 95]
Reversed:      [95 76 88 92 78 90 85]


### 5.4 2-D Slicing

In [16]:
table = np.array([
    [10, 20, 30, 40],
    [50, 60, 70, 80],
    [90, 100, 110, 120]
])

# First two rows, first two columns
print("First 2x2 block:")
print(table[:2, :2])
print()

# All rows, last column
print(f"Last column: {table[:, -1]}")

# Second row only
print(f"Second row:  {table[1, :]}")

First 2x2 block:
[[10 20]
 [50 60]]

Last column: [ 40  80 120]
Second row:  [50 60 70 80]


---

## 6. Reshaping Arrays

### 6.1 reshape() — Change the shape without changing data

In [17]:
arr = np.arange(12)   # [0, 1, 2, ..., 11]
print(f"Original: {arr}")
print(f"Shape: {arr.shape}")
print()

# Reshape to 3 rows × 4 columns
table = arr.reshape(3, 4)
print("Reshaped (3x4):")
print(table)
print()

# Reshape to 4 rows × 3 columns
table2 = arr.reshape(4, 3)
print("Reshaped (4x3):")
print(table2)

Original: [ 0  1  2  3  4  5  6  7  8  9 10 11]
Shape: (12,)

Reshaped (3x4):
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

Reshaped (4x3):
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


> ⚠️ **Rule:** Total elements must match!  
> 12 elements → can reshape to (3,4), (4,3), (2,6), (6,2), (12,1), (1,12)  
> 12 elements → CANNOT reshape to (3,5) because 3×5=15 ≠ 12

### 6.2 Using -1 (let NumPy figure it out)

In [18]:
arr = np.arange(12)

# "I want 3 rows, figure out the columns"
result1 = arr.reshape(3, -1)
print(f"reshape(3, -1) → shape {result1.shape}")
print(result1)
print()

# "I want 2 columns, figure out the rows"
result2 = arr.reshape(-1, 2)
print(f"reshape(-1, 2) → shape {result2.shape}")
print(result2)

reshape(3, -1) → shape (3, 4)
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

reshape(-1, 2) → shape (6, 2)
[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]]


### 6.3 Flatten & Ravel — Convert back to 1-D

In [19]:
table = np.array([[1, 2, 3], [4, 5, 6]])
print("Original:")
print(table)
print()

# flatten: returns a COPY (original unchanged)
flat = table.flatten()
print(f"flatten(): {flat}")

# ravel: returns a VIEW (changes affect original!)
flat_view = table.ravel()
print(f"ravel():   {flat_view}")

Original:
[[1 2 3]
 [4 5 6]]

flatten(): [1 2 3 4 5 6]
ravel():   [1 2 3 4 5 6]


### 6.4 Transpose — Swap rows and columns

In [20]:
table = np.array([
    [1, 2, 3],
    [4, 5, 6]
])
print("Original (2x3):")
print(table)
print()
print("Transposed (3x2):")
print(table.T)

Original (2x3):
[[1 2 3]
 [4 5 6]]

Transposed (3x2):
[[1 4]
 [2 5]
 [3 6]]


---

## 7. Array Operations (Math)

### 7.1 Element-wise Operations

In [21]:
a = np.array([10, 20, 30, 40])
b = np.array([1, 2, 3, 4])

print(f"a + b  = {a + b}")
print(f"a - b  = {a - b}")
print(f"a * b  = {a * b}")
print(f"a / b  = {a / b}")
print(f"a ** 2 = {a ** 2}")
print(f"a % 3  = {a % 3}")

a + b  = [11 22 33 44]
a - b  = [ 9 18 27 36]
a * b  = [ 10  40  90 160]
a / b  = [10. 10. 10. 10.]
a ** 2 = [ 100  400  900 1600]
a % 3  = [1 2 0 1]


> 🧠 **Key Insight:** Operations happen **element by element** — no loops needed!

### 7.2 Scalar Operations (one number applied to all)

In [22]:
marks = np.array([78, 85, 92, 67, 73])

# Add 5 bonus marks to everyone
new_marks = marks + 5
print(f"Original:    {marks}")
print(f"+5 bonus:    {new_marks}")

# Scale marks to out of 10
scaled = marks / 10
print(f"Out of 10:   {scaled}")

Original:    [78 85 92 67 73]
+5 bonus:    [83 90 97 72 78]
Out of 10:   [7.8 8.5 9.2 6.7 7.3]


### 7.3 Comparison Operations

In [23]:
marks = np.array([78, 85, 92, 67, 73])

print(f"marks > 80:  {marks > 80}")
print(f"marks == 92: {marks == 92}")
print(f"marks >= 73: {marks >= 73}")

marks > 80:  [False  True  True False False]
marks == 92: [False False  True False False]
marks >= 73: [ True  True  True False  True]


---

## 8. Broadcasting

Broadcasting is NumPy's way of handling arrays with **different shapes** during operations.

In [24]:
# Adding a column-wise bonus to a marks table
marks = np.array([
    [78, 85, 92],   # Student 1
    [67, 73, 88],   # Student 2
    [91, 84, 76]    # Student 3
])

# Different bonus for each subject: Math=5, Science=3, English=2
bonus = np.array([5, 3, 2])

# Broadcasting: bonus (1×3) is applied to each row (3×3)
new_marks = marks + bonus
print("Original marks:")
print(marks)
print(f"\nBonus per subject: {bonus}")
print("\nAfter bonus:")
print(new_marks)

Original marks:
[[78 85 92]
 [67 73 88]
 [91 84 76]]

Bonus per subject: [5 3 2]

After bonus:
[[83 88 94]
 [72 76 90]
 [96 87 78]]


> 🧠 **Rule of Broadcasting:**  
> NumPy compares shapes from the **right**. Dimensions are compatible if they are equal OR one of them is 1.

---

## 9. Useful NumPy Functions

### 9.1 Aggregation (Summary Statistics)

In [25]:
marks = np.array([78, 85, 92, 67, 73, 88, 91])

print(f"Sum:      {np.sum(marks)}")
print(f"Mean:     {np.mean(marks):.2f}")
print(f"Median:   {np.median(marks)}")
print(f"Std Dev:  {np.std(marks):.2f}")
print(f"Min:      {np.min(marks)}")
print(f"Max:      {np.max(marks)}")
print(f"Argmin:   {np.argmin(marks)} (index of min)")
print(f"Argmax:   {np.argmax(marks)} (index of max)")

Sum:      574
Mean:     82.00
Median:   85.0
Std Dev:  8.85
Min:      67
Max:      92
Argmin:   3 (index of min)
Argmax:   2 (index of max)


### 9.2 Axis — Row-wise vs Column-wise

> 🧠 **Memory Trick for Axis:**
> - `axis=0` → operation goes **DOWN** (collapses rows)
> - `axis=1` → operation goes **ACROSS** (collapses columns)

In [26]:
table = np.array([
    [85, 90, 78],   # Student 1
    [92, 88, 95],   # Student 2
    [67, 72, 80]    # Student 3
])
print("Table:")
print(table)
print()

# Sum of each column (axis=0 → move down rows)
col_sum = np.sum(table, axis=0)
print(f"Column sums (axis=0): {col_sum}")
print("  → Total Math=244, Science=250, English=253")
print()

# Sum of each row (axis=1 → move across columns)
row_sum = np.sum(table, axis=1)
print(f"Row sums (axis=1):    {row_sum}")
print("  → Student1=253, Student2=275, Student3=219")

Table:
[[85 90 78]
 [92 88 95]
 [67 72 80]]

Column sums (axis=0): [244 250 253]
  → Total Math=244, Science=250, English=253

Row sums (axis=1):    [253 275 219]
  → Student1=253, Student2=275, Student3=219


### 9.3 Sorting

In [27]:
arr = np.array([42, 15, 88, 3, 67])

print(f"Original:    {arr}")
print(f"Sorted (↑):  {np.sort(arr)}")
print(f"Sorted (↓):  {np.sort(arr)[::-1]}")
print(f"Sort indices: {np.argsort(arr)}")

Original:    [42 15 88  3 67]
Sorted (↑):  [ 3 15 42 67 88]
Sorted (↓):  [88 67 42 15  3]
Sort indices: [3 1 0 4 2]


### 9.4 Unique Values

In [28]:
grades = np.array(['A', 'B', 'A', 'C', 'B', 'A', 'D', 'C'])

unique_vals, counts = np.unique(grades, return_counts=True)
print(f"Unique grades: {unique_vals}")
print(f"Counts:        {counts}")

Unique grades: ['A' 'B' 'C' 'D']
Counts:        [3 2 2 1]


### 9.5 Mathematical Functions

In [29]:
# Trigonometry
angles = np.array([0, 30, 45, 60, 90])
radians = np.radians(angles)

print(f"Angles:  {angles}°")
print(f"sin:     {np.round(np.sin(radians), 3)}")
print(f"cos:     {np.round(np.cos(radians), 3)}")
print()

# Square root and log
print(f"sqrt([4, 9, 16, 25]): {np.sqrt(np.array([4, 9, 16, 25]))}")
print(f"log([1, 10, 100]):    {np.round(np.log(np.array([1, 10, 100])), 2)}")

Angles:  [ 0 30 45 60 90]°
sin:     [0.    0.5   0.707 0.866 1.   ]
cos:     [1.    0.866 0.707 0.5   0.   ]

sqrt([4, 9, 16, 25]): [2. 3. 4. 5.]
log([1, 10, 100]):    [0.   2.3  4.61]


---

## 10. Stacking & Splitting

### 10.1 Stacking (Combining Arrays)

In [30]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

# Vertical stack (stack as rows)
print("vstack:")
print(np.vstack((a, b)))
print()

# Horizontal stack (stack side by side)
print(f"hstack: {np.hstack((a, b))}")

vstack:
[[1 2 3]
 [4 5 6]]

hstack: [1 2 3 4 5 6]


### 10.2 Splitting (Breaking Arrays Apart)

In [31]:
arr = np.array([10, 20, 30, 40, 50, 60])

# Split into 3 equal parts
parts = np.split(arr, 3)
print("Split into 3 equal parts:")
for i, part in enumerate(parts):
    print(f"  Part {i+1}: {part}")

print()

# Split at specific positions
parts2 = np.split(arr, [2, 4])
print("Split at positions [2, 4]:")
for i, part in enumerate(parts2):
    print(f"  Part {i+1}: {part}")

Split into 3 equal parts:
  Part 1: [10 20]
  Part 2: [30 40]
  Part 3: [50 60]

Split at positions [2, 4]:
  Part 1: [10 20]
  Part 2: [30 40]
  Part 3: [50 60]


---

## 11. Boolean Indexing & Filtering

This is one of NumPy's **superpowers** — filter data without loops!

In [32]:
marks = np.array([78, 85, 92, 67, 73, 88, 91, 55, 60])

# Find all marks above 80
high_scores = marks[marks > 80]
print(f"Marks above 80: {high_scores}")

# Find marks between 70 and 90
mid_range = marks[(marks >= 70) & (marks <= 90)]
print(f"Marks 70-90:    {mid_range}")

# Count how many students scored above 80
print(f"Count above 80: {np.sum(marks > 80)}")

Marks above 80: [85 92 88 91]
Marks 70-90:    [78 85 73 88]
Count above 80: 4


### np.where() — If-Else for arrays

In [33]:
marks = np.array([78, 85, 45, 92, 38, 88])

# Pass/Fail based on marks
result = np.where(marks >= 50, 'Pass', 'Fail')
print(f"Marks:  {marks}")
print(f"Result: {result}")

Marks:  [78 85 45 92 38 88]
Result: ['Pass' 'Pass' 'Fail' 'Pass' 'Fail' 'Pass']


---

## 12. Random Numbers

In [34]:
# Random float between 0 and 1
print(f"Random float: {np.random.rand()}")
print()

# Random array (2×3) between 0 and 1
print("Random 2x3 array:")
print(np.random.rand(2, 3))
print()

# Random integers
print(f"5 random ints (1-99): {np.random.randint(1, 100, size=5)}")
print()

# Random from normal distribution (mean=0, std=1)
print(f"Normal distribution: {np.round(np.random.randn(5), 2)}")

Random float: 0.162274780065516

Random 2x3 array:
[[0.82423646 0.41683504 0.35446274]
 [0.93687083 0.11757934 0.29724748]]

5 random ints (1-99): [95 12 34 74 59]

Normal distribution: [-1.93  0.04  0.59  0.72  2.17]


In [35]:
# Shuffle an array (in-place)
arr = np.array([1, 2, 3, 4, 5])
np.random.shuffle(arr)
print(f"Shuffled: {arr}")

# Reproducible results (same random numbers every time)
np.random.seed(42)
print(f"Seeded random: {np.random.rand(3)}")

np.random.seed(42)  # Same seed = same output!
print(f"Same seed:     {np.random.rand(3)}")

Shuffled: [5 4 3 1 2]
Seeded random: [0.37454012 0.95071431 0.73199394]
Same seed:     [0.37454012 0.95071431 0.73199394]


---

## 13. Copying vs Viewing

### ⚠️ This is a common source of bugs!

In [36]:
# VIEW — shares the same data
original = np.array([1, 2, 3, 4, 5])
view = original[1:4]
view[0] = 99
print(f"After modifying VIEW:")
print(f"  Original: {original}  ← Changed! 😱")
print()

# COPY — independent copy
original = np.array([1, 2, 3, 4, 5])
copy = original[1:4].copy()
copy[0] = 99
print(f"After modifying COPY:")
print(f"  Original: {original}  ← Safe! ✅")

After modifying VIEW:
  Original: [ 1 99  3  4  5]  ← Changed! 😱

After modifying COPY:
  Original: [1 2 3 4 5]  ← Safe! ✅


> 💡 **Rule of Thumb:** Use `.copy()` when you want to modify sliced data without affecting the original.

---

## 14. 🎯 Real-World Mini Project: Student Grade Calculator

In [37]:
import numpy as np

# 5 students, 4 subjects
marks = np.array([
    [85, 90, 78, 88],   # Alice
    [92, 88, 95, 91],   # Bob
    [67, 72, 80, 75],   # Charlie
    [55, 60, 45, 50],   # David
    [98, 95, 92, 97]    # Eve
])

students = ['Alice', 'Bob', 'Charlie', 'David', 'Eve']
subjects = ['Math', 'Science', 'English', 'History']

# Average marks per student
avg_per_student = np.mean(marks, axis=1)
print("📊 Average per student:")
for name, avg in zip(students, avg_per_student):
    print(f"   {name}: {avg:.1f}")
print()

# Highest scorer
best_idx = np.argmax(avg_per_student)
print(f"🏆 Topper: {students[best_idx]} with {avg_per_student[best_idx]:.1f} avg")
print()

# Subject with highest average
avg_per_subject = np.mean(marks, axis=0)
best_subj_idx = np.argmax(avg_per_subject)
print(f"📚 Easiest subject: {subjects[best_subj_idx]} (avg: {avg_per_subject[best_subj_idx]:.1f})")
print()

# Students who passed all subjects (passing = 50)
all_passed = np.all(marks >= 50, axis=1)
print(f"✅ Passed all subjects: {[s for s, p in zip(students, all_passed) if p]}")

📊 Average per student:
   Alice: 85.2
   Bob: 91.5
   Charlie: 73.5
   David: 52.5
   Eve: 95.5

🏆 Topper: Eve with 95.5 avg

📚 Easiest subject: Science (avg: 81.0)

✅ Passed all subjects: ['Alice', 'Bob', 'Charlie', 'Eve']


## 15. 🎯 Mini Project 2: Simple Image as Array

In [38]:
import numpy as np

# A grayscale image is just a 2D array of pixel values (0=black, 255=white)
image = np.random.randint(0, 256, size=(100, 100))

# Make it brighter (increase all pixel values by 50)
brighter = np.clip(image + 50, 0, 255)   # clip to stay in valid range

# Invert the image (like a negative)
inverted = 255 - image

print(f"Image shape:          {image.shape}")
print(f"Original brightness:  {np.mean(image):.1f}")
print(f"Brighter version:     {np.mean(brighter):.1f}")
print(f"Inverted version:     {np.mean(inverted):.1f}")

Image shape:          (100, 100)
Original brightness:  127.7
Brighter version:     172.8
Inverted version:     127.3


---

## 📝 Quick Cheat Sheet

```
CREATION:
  np.array([1,2,3])          → from list
  np.zeros((r,c))            → all zeros
  np.ones((r,c))             → all ones
  np.full((r,c), value)      → all same value
  np.arange(start,stop,step) → sequence
  np.linspace(start,stop,n)  → n evenly spaced
  np.identity(n)             → identity matrix
  np.random.rand(r,c)        → random 0-1

INSPECTION:
  arr.shape   arr.dtype   arr.size   arr.ndim

MANIPULATION:
  arr.reshape(r,c)   arr.flatten()   arr.ravel()   arr.T

MATH:
  np.sum()  np.mean()  np.std()  np.min()  np.max()

FILTERING:
  arr[arr > 5]              → boolean indexing
  np.where(condition, x, y) → if-else
```

---

> 🎉 **Congratulations!** You now know the essentials of NumPy!  
> **Next up:** Learn **Pandas** for working with tables and datasets!